### PR TITLE
Add install section to gazebo_version_helpers

### PR DESCRIPTION
**Pull request by MoriKen254**
Added install section in CMakeLists.txt of gezebo_version_helpers.

This helped my repo using your packages pass industrial_ci test on Travis CI.

Hope it'll be accepted.

### CODE REVIEW

**Comment by JenniferBuehler** [comment]
Oh I forgot to do that, thanks!

**Comment by JenniferBuehler** [comment]
This now has conflicts after some updates, can you please resolve and I'll merge. Thanks :)

**Comment by MoriKen254** [comment]
Fixed conflicts and small format issues! hope this will be merged.

**Comment by MoriKen254** [comment]
thanks for merging :)

**Pull request merged**
